#!/bin/bash -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE master1 WITH ENCRYPTED PASSWORD 'theSecret3st1' SUPERUSER LOGIN;

    CREATE ROLE web INHERIT;
    CREATE DATABASE web;
    GRANT ALL PRIVILEGES ON DATABASE web TO web;

    CREATE USER web1 WITH ENCRYPTED PASSWORD 'secretpassword';
    GRANT web to web1;
EOSQL
